# Generated by Django 5.0.1 on 2024-03-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_logo',
            field=models.FileField(upload_to='movie_logos/'),
        ),
    ]
